/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test1;

import java.io.IOException;

public class App {

    public static void main(String[] args) {
        GameLoop game = new GameLoop();
        try{game.Loop();} catch(IOException e){System.out.println("error");} catch(InterruptedException e){System.out.println("error2");}
    }
}
